version: 2.1
jobs:
  build-and-test-server:
    docker:
      - image: circleci/node:12.16.2
    working_directory: ~/app-server
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd api/
            npm i
      - run:
          name: Move assets into deploy directory
          command: |
            mkdir api-deploy
            cd api/
            mv src/ manifest.yml package.json gc-config.js node_modules/ ../api-deploy
      - persist_to_workspace:
          root: ~/app-server
          paths:
            - api-deploy/

  deploy-server:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/app-server
      - run:
          name: Deploy server to cloud.gov.au development
          command: |
            cd ~/app-server
            cd api-deploy/
            cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
            cf zero-downtime-push -f manifest.yml

  build-and-test-front-end:
    docker:
      - image: circleci/node:12.16.2
    working_directory: ~/app-ui
    steps:
      - checkout
      - run:
          name: Install dependencies set envs
          command: |
            cd front-end/
            npm i
            . ./prebuild.sh
            npm run build
      - run:
          name: Make deploy directory
          command: |
            mkdir front-end-deploy
            cd front-end
            mv manifest.yml public/ ../front-end-deploy
      - persist_to_workspace:
          root: ~/app-ui
          paths:
            - front-end-deploy/

  deploy-front-end:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/app-ui
      - run:
          name: Deploy to cloud.gov.au development
          command: |
            cd ~/app-ui
            cd front-end-deploy/
            cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
            cf zero-downtime-push -f manifest.yml

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-and-test-server
      - deploy-server:
          requires:
            - build-and-test-server
          filters:
            branches:
              only: master
      - build-and-test-front-end
      - deploy-front-end:
          requires:
            - build-and-test-front-end
          filters:
            branches:
              only: master
